name: ICP and NPM Start Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Clang
      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
          clang --version

      # Download and install DFX CLI manually (non-interactive)
      - name: Install DFX CLI
        run: |
          DFX_VERSION=0.13.1  # Specify the desired version of dfx
          DFX_INSTALL_DIR="$HOME/.local/share/dfx"
          DFX_BIN_DIR="$DFX_INSTALL_DIR/bin"

          # Create the directory and download the dfx binary
          mkdir -p $DFX_BIN_DIR
          curl -L https://github.com/dfinity/sdk/releases/download/$DFX_VERSION/dfx-$DFX_VERSION-x86_64-linux.tar.gz | tar -xz -C $DFX_BIN_DIR

          # Add dfx to the PATH
          echo "export PATH=$DFX_BIN_DIR:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

          # Verify dfx installation
          dfx --version

      # Start DFX in the background with clean slate
      - name: Start DFX
        run: |
          dfx start --background --clean
          sleep 10  # Wait for DFX to initialize

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Run the application
      - name: Run NPM start
        run: npm start
