name: ICP Build and Deploy

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies for building the project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      # Step 3: Install DFX ICP CLI
      - name: Install DFX
        run: |
          wget -O- https://sdk.dfinity.org/install.sh | bash
          echo "::add-path::$HOME/.dfx/bin"

      # Step 4: Verify DFX installation
      - name: Verify DFX Installation
        run: dfx --version

      # Step 5: Start DFX replica in the background
      - name: Start DFX Replica
        run: dfx start --clean --background

      # Step 6: Wait for the replica to be ready
      - name: Wait for DFX Replica to Start
        run: sleep 10

      # Step 7: Deploy canisters
      - name: Deploy Canisters
        run: dfx deploy

      # Step 8: Install NPM dependencies
      - name: Install NPM Dependencies
        run: npm install

      # Step 9: Start the application
      - name: Start Application
        run: npm start
